services:
  db:
    image: postgres:15
    container_name: lumo_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lumo}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lumo_backend
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${POSTGRES_DB:-lumo};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD}"
      Jwt__Key: "${JWT_KEY}"
      Jwt__Issuer: https://localhost:5001
      Jwt__Audience: https://localhost:5001
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    # For hot reloading, we mount source code and use dotnet watch
    volumes:
      - ./server:/app
      - /app/bin
      - /app/obj
    working_dir: /app

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      target: development
    container_name: lumo_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    environment:
      VITE_API_URL: http://backend:5000
      NODE_ENV: development
    depends_on:
      - backend

volumes:
  postgres_data:
