version: '3.8'

services:
  db:
    image: postgres:15
    container_name: projectmanagement_db
    restart: always
    environment:
      POSTGRES_DB: projectmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: projectmanagement_backend
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=projectmanagement;Username=postgres;Password=password
      Jwt__Key: YourSuperSecretKeyThatIsAtLeast32CharactersLongForHS256
      Jwt__Issuer: https://localhost:5000
      Jwt__Audience: https://localhost:5000
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
    working_dir: /app

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: projectmanagement_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    environment:
      VITE_API_URL: http://localhost:5000

volumes:
  postgres_data:
