services:
  db:
    image: postgres:15
    container_name: lumo_db_prod
    restart: always
    environment:
      POSTGRES_DB: lumo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: lumo_backend_prod
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=lumo;Username=postgres;Password=${POSTGRES_PASSWORD:-password}"
      Jwt__Key: "${JWT_KEY:-YourSuperSecretKeyThatIsAtLeast32CharactersLongForHS256!}"
      Jwt__Issuer: https://yourdomain.com
      Jwt__Audience: https://yourdomain.com
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: lumo_frontend_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data_prod:
