FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy the project file and restore dependencies
COPY Lumo.csproj ./
RUN dotnet restore

# Copy the entire source code
COPY . ./

# Publish the application for production
RUN dotnet publish -c Release -o out

# Production image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 5000

ENTRYPOINT ["dotnet", "Lumo.dll"]
